import React, { useEffect } from 'react';
import ExecutiveSummary from '../sections/audit/ExecutiveSummary';
import ComponentInventory from '../sections/audit/ComponentInventory';
import ConsistencyScorecard from '../sections/audit/ConsistencyScorecard';
import CriticalFindings from '../sections/audit/CriticalFindings';
import DriftDetection from '../sections/audit/DriftDetection';
import StandardizationRecommendations from '../sections/audit/StandardizationRecommendations';
import AuditFooter from '../components/audit/AuditFooter';
import Header from '../components/Header';
import BackToTop from '../components/BackToTop';

const AuditReport = () => {
  useEffect(() => {
    const observerOptions = {
      threshold: 0.1,
      rootMargin: '0px 0px -50px 0px'
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          entry.target.classList.add('visible');
        }
      });
    }, observerOptions);

    const revealElements = document.querySelectorAll('.reveal, .reveal-left');
    revealElements.forEach(el => observer.observe(el));

    return () => observer.disconnect();
  }, []);

  const navLinks = [
    { name: 'Summary', href: '#summary' },
    { name: 'Inventory', href: '#inventory' },
    { name: 'Scorecard', href: '#scorecard' },
    { name: 'Findings', href: '#findings' },
    { name: 'Drift', href: '#drift' },
    { name: 'Standardization', href: '#recommendations' },
  ];

  return (
    <div className="min-h-screen transition-colors duration-500" style={{ backgroundColor: 'var(--app-bg)', color: 'var(--app-text)' }}>
      <Header />
      
      {/* Report Header / Sub-nav */}
      <nav className="fixed top-20 left-0 w-full z-40 backdrop-blur-md border-b transition-colors duration-500 py-5 px-6 md:px-12" style={{ backgroundColor: 'var(--app-bg)', opacity: 0.9, borderColor: 'var(--app-border)' }}>
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="text-primary">
                <circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="1.5"/>
                <circle cx="12" cy="12" r="3" stroke="currentColor" strokeWidth="2"/>
                <path d="M12 3V5M12 19V21M3 12H5M19 12H21" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
                <path d="M16 8L18 6M6 18L8 16M18 18L16 16M8 8L6 6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
            </svg>
            <span className="text-[11px] font-mono text-primary uppercase tracking-[0.2em] font-medium">Report_ID</span>
            <span className="text-[11px] font-mono uppercase tracking-widest opacity-70">SL-2026-0503-A</span>
          </div>
          
          <div className="hidden lg:flex items-center gap-10">
            {navLinks.map((link) => (
              <a 
                key={link.name} 
                href={link.href}
                className="text-[11px] font-mono uppercase tracking-[0.15em] opacity-40 hover:text-primary hover:opacity-100 hover:tracking-[0.2em] transition-all duration-300"
              >
                {link.name}
              </a>
            ))}
          </div>
          
          <div className="flex items-center gap-2 px-3 py-1 bg-primary/5 border" style={{ borderColor: 'var(--app-border)' }}>
            <div className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse" />
            <span className="text-[10px] font-mono uppercase tracking-widest opacity-80">Live Analysis</span>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-6 md:px-12 pt-48 pb-20">
        <header className="mb-24 reveal">
          <h1 className="text-6xl md:text-9xl font-display leading-none tracking-tight mb-8">
            System <br />
            Audit Report
          </h1>
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-12">
            <p className="max-w-2xl text-xl font-sans font-light leading-relaxed opacity-60">
              A comprehensive technical evaluation of the component architecture, 
              visual consistency, and design system resilience. Generated by 
              <span className="font-medium opacity-100"> Second Look Intelligence Platform</span>.
            </p>
            <div className="text-[11px] font-mono uppercase tracking-[0.3em] text-right border-l pl-8 opacity-30" style={{ borderColor: 'var(--app-border)' }}>
              Executed: May 03, 2026 <br />
              Location: Production_Edge
            </div>
          </div>
        </header>

        <ExecutiveSummary />
        <ComponentInventory />
        <ConsistencyScorecard />
        <CriticalFindings />
        <DriftDetection />
        <StandardizationRecommendations />
      </main>

      <AuditFooter />
      <BackToTop />
    </div>
  );
};

export default AuditReport;
